name: SAM CI/CD

on:
  pull_request:
    branches:
      - master
    paths:
      - 'sam-comprehend/**'
  push:
    branches:
      - master
    paths:
      - 'sam-comprehend/**'

jobs:
  sam:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      # Pull Request / Build Steps
      - name: SAM Validate
        working-directory: ./sam-comprehend
        if: github.event_name == 'pull_request'
        env:
          AWS_REGION: eu-west-1
        run: sam validate

      - name: SAM Build
        working-directory: ./sam-comprehend
        if: github.event_name == 'pull_request'
        env:
          AWS_REGION: eu-west-1
        run: sam build

      # Push to main / Deploy Steps
      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: SAM Validate
        working-directory: ./sam-comprehend
        if: github.event_name == 'push'
        env:
          AWS_REGION: eu-west-1
        run: sam validate

      - name: SAM Build
        working-directory: ./sam-comprehend
        if: github.event_name == 'push'
        env:
          AWS_REGION: eu-west-1
        run: sam build

      - name: SAM Deploy
        working-directory: ./sam-comprehend
        if: github.event_name == 'push'
        env:
          AWS_REGION: eu-west-1
        run: |
          sam deploy \
            --stack-name kandidat-58-sentiment \
            --s3-bucket kandidat-58-data \
            --capabilities CAPABILITY_IAM \
            --region $AWS_REGION \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
